### ISSUE TITLE
Don't display user's own Offers and Wants in Marketplace

### ISSUE THREAD

**Issue by tfwoodroofMCS** [CredComSoc/CreditCoopTech#108]
At present, users see their own Offers and Wants in the Marketplace. This makes it unnecessarily hard to find what others have posted, and so user's own items should not be displayed.

**Comment by utunga** [comment]
Dang it - too late now but I would have advised against this. I am concerned people need to be able to see what is going on. If they can't see their own products I'm pretty sure we'll get people thinking that they can't post things to the shop because it doesn't appear.

@tfwoodroofMCS I won't reopen this but let's maybe seek feedback on this one and/or maybe keep an eye out for it.

**Comment by abecollins** [comment]
100% agreement with Miles. Abe
