### ISSUE TITLE
Set up support email and content

### ISSUE THREAD

**Issue by dilgreen** [CredComSoc/CreditCoopTech#28]
A landcaretrade.coop support email needs setting up.

This should be distinct from the 'contact us' email, since that will likely be routed to Abe, while support should come to MCS.

I propose support@landcaretrade.com

- [ ] set up landcaretrade.com emails - check with Abe to see if he would like MCS to manage this (which we can do through migadu)
- [ ] instutute a mail sending service - migadu initially (out of scope for this issue: we do need to work towards a company-wide move to a specialist transactional email supplier)
- [ ] add support@landcaretrade.com to the code in all instances where it applies - please add below
    - [ ] login screen
    - [ ] contact
    - [ ] en-LCC.json

**Comment by tfwoodroofMCS** [comment]
@EugeneJoe - Dil and Miles are sorting this one out.

**Comment by tfwoodroofMCS** [comment]
Next steps:

- [ ] Miles to set up support inbox & send password to Yani
- [ ] Miles to confirm with Tom W that he can access via Migadu admin panel and set up forwarding to personal mailbox.

**Comment by utunga** [comment]
@yonasbek I've set up an email 'mailbox' for support@landcaretrade.com 
@tfwoodroofMCS I set up forwarding to your account for now - but if you could log in to migadu check the landcaretrade.com domain mayaybe confirm you can send. 

@yonasbek I will send you the password in DM.. but here's all the different ways yuo should be able to access the support mailbox to send email. 


[FireShot Capture 001 - Migadu.com - admin.migadu.com.pdf](https://github.com/CredComSoc/CreditCoopTech/files/12671876/FireShot.Capture.001.-.Migadu.com.-.admin.migadu.com.pdf)

**Comment by yonasbek** [comment]
@tfwoodroofMCS can you give more explanation on this issue please. Specifically what i need to do

**Comment by utunga** [comment]
Hi.. I know you asked @tfwoodroofMCS .. so, Tom, perhaps you can correct me if I get this wrong. But as far as i understand things..

Yonas, if you sign up as a user and use your own email address you should receive emails about your account as you do this? The events that trigger these things can be seen in the code.

What remains (perhaps ?)is to hook up nodemailer or probably a better/newer equivalent so that actual emails get sent.

**Acceptance Criteria**

- We need to ensure that those emails are being received by the end user.

- We need to verify/ensure that if a user hits reply and creates an email to support@landcaretrade.com that Tom receives that email via his forwarding address.

That scope may have already been covered in other issues but once we can verify that I think we're good to go here.

Hope this was helpful. 

 PS A bit meta but if we couldve written a clear AC at the start and had issues at the 'desired outcome' level rather than the 'do this thing' level  it might have been less confusing

**Comment by dilgreen** [comment]
This makes no sense to me; "if you sign up as a user and use your own email address you should receive emails about your account as you do this? "

A 'user' cannot 'sign-up' to coopcredit. They have to be added as part of an admin process.

We do need to make a decision on a bulk/transactional email service.

Dil

Miles Thompson wrote on 24/09/2023 10:31:

**Comment by tfwoodroofMCS** [comment]
@yonasbek - me and Dil have just worked out the next steps:

- [ ] @dilgreen to ask Abe for welcome email texts
- [ ] Check that [support@landcaretrade.com](mailto:support@landcaretrade.com) has been added to the code in all instances where it applies - please add below
   - [ ]  login screen
   - [ ]  contact
   - [ ]  en-LCC.json
- [ ] Make password reset available to users (see #142).

Whilst volume remains very small, Migadu will be good enough (but will implement nodemailer as per Miles' suggestion when necessary).

**Comment by utunga** [comment]
we're already set up on migadu.. i meant id you create a user with your email address
