### ISSUE TITLE
purchase completes when balance insufficient (heisenbug)

### ISSUE THREAD

**Issue by dilgreen** [CredComSoc/CreditCoopTech#35]
When purchasing, the app should not allow me to buy if the purchase would  take me beyond my balance limit. 
This *is* working in the Svensk Barter version - but with this version we are using a newer version of the CredCom ledger service, so maybe that's the problem?

To reproduce - try to buy something with test user that would go beyond the available credit.

**Comment by utunga** [comment]
suggestion you may want to use httpie to debug things

**Comment by utunga** [comment]
@dilgreen can you test this again? cc-node was crashing earlier but if its up it seems to work ok.

**Comment by tfwoodroofMCS** [comment]
Tested this just now, and was able to complete a purchase request even if it would take the buyer beyond their balance limit:

![signal-2023-08-18-200149](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/7c9ad2da-3cda-4dca-9e42-6c23956eb7d3)

The seller also gets a notification, but when going to My account -> Wants to view purchase requests [see #67 for notes on dysfunctionality here], there isn't anything there.

**Comment by tfwoodroofMCS** [comment]
Just tested this with a transaction that would have been within the buyer's limits, and same result - seller can't see purchase request.

**Comment by utunga** [comment]
Seems like it correctly prevents user over-spend with testuser3 (or on Yonas' computer) but it doesnt work in test

**Comment by tfwoodroofMCS** [comment]
Let me know as soon as it would be useful for me to do some more testing.

**Comment by utunga** [comment]
@tfwoodroofMCS other's have volunteered to look into this particular bug but it certainly wouldn't hurt for you to try and test it a bit more. 

What happened during our call last night was 
- @yonasbek showed us (during a screenshare) that, with `testuser3` he was prevented from overspending
- Meanwhile @dilgreen confirmed that with `testuser` he *wasn't* prevented from overspending.

It may be due to the thing that was being bought or it may be to do with what was being purchased. Or it may be the timing, or maybe who you're purchasing from. Or maybe it's sunspots. Either way certainly wouldn't be unhelpful to figure out when it does and doesn't happen.

That said I think @yonasbek is going to look into this on the code side and may be able to figure out hte problem there.

**Comment by utunga** [comment]
Thanks @yonasbek #85 should hopefully fix this one

**Comment by tfwoodroofMCS** [comment]
Tested this for 'old' test users (testuser and testuser2) with different balance limit violations and an acceptable transaction. If necessary, can come back later and attempt to reproduce these results for 'new' test users, as @yonasbek observed different outcome for testuser3.

- Purchase request from _testuser_ to _testuser2_ that would not have violated _testuser_'s negative limit, but would have taken _testuser2_ beyond their positive balance limit (NB: this isn't actually stated anywhere, so I'm assuming it's 500 pollen). **Results**: 
** Message to _testuser_ saying  'Unable to complete the transaction'. As expected, but not a helpful error message - no indication that the problem is with testuser2 having an excessive balance (assuming that the app is in fact actually behaving correctly, i.e. the transaction was blocked because of this, and not for some other reason). 
** App returns _testuser_ to home screen, item remains in cart: acceptable behaviour. 
** _testuser2_ gets a notification: 'You have received a purchase request from _testuser_. Go to My account to approve or decline..': this shouldn't happen. As per [earlier comment](https://github.com/CredComSoc/CreditCoopTech/issues/35#issuecomment-1684329489), there is nothing in My account -> Trades -> Purchase requests, which is in fact as it should be, and won't be a problem once the notification no longer appears.

- Purchase request from _testuser_ to _testuser2_ that would have taken _testuser_ beyond their negative balance limit, but not taken _testuser2_ beyond their (assumed) positive balance limit. **Results**: 
** Message to _testuser_ saying that purchase could not be completed due to insufficient credit. As expected. 
** App returns to home screen, item remains in cart: acceptable behaviour.
** testuser2 does not receive a notification, as expected.

- Purchase request from _testuser_ to _testuser2_ that would have taken _testuser_ beyond their negative balance limit, and _testuser2_ beyond their (assumed) positive balance limit. **Results**: 
** Message to _testuser_ saying that purchase could not be completed due to insufficient credit. As expected (but error message could also indicate that in this case _testuser2_ would also need to modify their balance). 
** App returns to home screen, item remains in cart: acceptable behaviour.
** testuser2 does not receive a notification, as expected.

- Purchase request from _testuser2_ to _testuser_ that doesn't violate either's balance limits. **Results**: 
** Message to _testuser2_ saying  'Unable to complete the transaction', which is wrong as the request does actually seem to go through (see below). 
** App returns to home screen, item remains in cart: returning to home screen is fine, but (again given that the request goes through), item should be removed from cart. 
** _testuser_ gets a notification: 'You have received a purchase request from _testuser2_. Go to My account to approve or decline..': this is as expected (although see #39).
** Purchase request appears for _testuser_ in My account -> Trades -> Purchase requests, with an option to approve or decline.
** If approve: _testuser_ sees status in Purchase requests updated to 'approved', balance updates as expected, and item is moved to 'Sales History': all as expected (albeit with poor performance - multiple refreshes required). _testuser2_ gets a notification saying 'test_user har godkänt din köpförfrågen. Go to My account to download the invoice' and balance updates as expected, and the item appears under My account -> Trades -> Sales History (but is not that easy to find, as this heading doesn't indicate that purchase history is kept here as well): all as expected.
** If decline: _testuser_ initially sees status in Purchase requests updated to 'declined', but refreshing the page redisplays the request as needing approval or decline. Balance stays the same, as expected, and nothing appears in My account -> Trades -> Sales History, as expected. _testuser2_ gets a notification saying 'test_user has denied your purchase request', as expected. Balance stays the same, as expected, and item does not appear in Sales History, as expected, but a whole load of Swedish ('Du har väntande köp som ska...') appears under Pending Purchases, which translates to 'You have pending purchases that must be approved by the buyer before the purchase is completed. You will receive a notice when the buyer has approved the purchase.' This presumably appeared after _testuser2_ made the request, and is a useful message (although note that it should read 'approved by the seller' and 'seller has approved the purchase'), but should be deleted as soon as the purchase request is denied.

**Comment by dilgreen** [comment]
It occurs to me that most of this team has never had sight of any documentation as to expected behaviours or features (such as positive balance limits).
More documentation needed.

**Comment by tfwoodroofMCS** [comment]
Observations in my previous comment have been translated into issues #86 through to #96 (plus #98 for making positive credit limits visible).
