### ISSUE TITLE
Review notifications

### ISSUE THREAD

**Issue by dilgreen** [CredComSoc/CreditCoopTech#39]
Links in notifications do not always take the user to where they would expect to arrive.

Review these.

**Comment by tfwoodroofMCS** [comment]
Review also language used in notifications.

**Comment by tfwoodroofMCS** [comment]
- [ ] Update text in cancelled purchase request notification to seller to '`buyer username` has cancelled their purchase request for `item name 1`, `item name 2` and `item name 3`' (listing item names as appropriate).
- [ ] Update text in declined purchase request notification to buyer to '`seller username` has declined your purchase request for `item name 1`, `item name 2` and `item name 3`' (listing item names as appropriate).

**Comment by tfwoodroofMCS** [comment]
@EugeneJoe, assigning this to you as the items above go beyond just minor English text edits.

**Comment by tfwoodroofMCS** [comment]
@EugeneJoe - doing a global search for `my_account` returns 8 results in Notifications.vue (which I'm guessing contains the notifications table you built the other week?). Looking at the code, all 8 should be replaced with `my_trades`.

**Comment by tfwoodroofMCS** [comment]
Notification to seller about cancelled purchase request doesn't seem to have been implemented as specified - see top notification in screenshot:

![Image](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/f29c7a94-11a1-4d83-8b43-61383eeea720)

However, during testing I realised that the original specification was slightly wrong - although purchase requests can include multiple items, cancellations apply to individual items, rather than the request as a whole. This means that the notification should read: '`buyer username` has cancelled their purchase request for `item name`.'

**Comment by tfwoodroofMCS** [comment]
Similarly, notification to buyer that their purchase request has been declined has not been implemented correctly:

![Image](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/88dd4bfa-9025-4fca-a017-cdf6c6c1d75f)

As with the previous, message should include `item name` (but again, items are declined individually, so no need for a list).

**Comment by tfwoodroofMCS** [comment]
Notification text now reads 'My trades' rather 'My account', as specified, but the link still directs to the My profile subsection, rather than My trades.

**Comment by EugeneJoe** [comment]
Note to self: Will need to add item no and item name to notifications.

**Comment by EugeneJoe** [comment]
Done

**Comment by tfwoodroofMCS** [comment]
@EugeneJoe in notifications for cancelled purchase requests, `number of units` and `item name` not implemented correctly. Text also needs to read 'purchase request' (rather than just 'purchase'): 

![Image](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/11c8e7a7-9b71-410a-9ee9-abede0e20059)

**Comment by tfwoodroofMCS** [comment]
Also need to create a notification to recipient for cancelled transfer requests: '`sender username` has cancelled their transfer request for `transfer amount` `credit unit`.'

**Comment by tfwoodroofMCS** [comment]
Notification to sender of declined transfer request needs to include `transfer amount` and `credit unit`:

![Image](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/dcd12bf2-170d-4b14-9b2a-3aa6c8134220)

**Comment by tfwoodroofMCS** [comment]
@yonasbek, can the notifications table support the various `amount` changes in the above three comments, or - similarly to the calculations in #202 - will it have to wait for new functionality?

**Comment by EugeneJoe** [comment]
@tfwoodroofMCS For the cancelled purchase request, was this a new notification or an old existing one?
I changed how we create some of the notifications to include number of units and item name. This won't reflect in the old notifications though.

**Comment by tfwoodroofMCS** [comment]
@EugeneJoe - as best I can recall, the cancelled purchase request notification is an old one.

Have just done some testing, and the cancelled purchase request notification does an odd thing: it initially appears correctly, then changes so that the `number of units` and `item name` disappear:

https://github.com/CredComSoc/CreditCoopTech/assets/105865183/dc21ff16-bebf-47ae-becf-da27f4339184

Please could you look into this?

NB: It is working correctly for declined requests:

https://github.com/CredComSoc/CreditCoopTech/assets/105865183/cc5598a4-8390-4d52-82fa-25509d294ef5

Declined transfer request notification text is as specified, but there appears to be something odd going on with its display: the yellow dot appears, but the notification text takes a while to appear, and when it does it's under 'Older':

https://github.com/CredComSoc/CreditCoopTech/assets/105865183/ef5b113d-987d-41b8-bf25-6f907900df1c

Have reproduced this three times, so whilst it may be a slow server issue, please could you check for bugs?

Notification of cancelled transfer request is as specified - good job!
