### ISSUE TITLE
Internationalise admin panel

### ISSUE THREAD

**Issue by utunga** [CredComSoc/CreditCoopTech#72]
![Image](https://user-images.githubusercontent.com/166867/261593305-0221f0aa-a7e7-40d8-977b-84f55ac0efbf.png)

**Comment by tfwoodroofMCS** [comment]
In order to be consistent with other references to these parameters, 'Default balance limits' should be 'Default credit limits', 'Maximum' should be 'Positive' and 'Minimum' should be 'Negative'.

**Comment by tfwoodroofMCS** [comment]
Lots of other things to fix here, but putting in mañana as not urgent - in particular, won't be using admin panel to add users.

**Comment by tfwoodroofMCS** [comment]
@EugeneJoe - modifying this issue to list all Swedish instances (plus other minor language changes) so that they can be internationalised:

- [ ] On landing screen:
   - [ ] Replace instances of 'bKr' under 'Balance' in table with `credit unit` (abbreviated version)
   - [ ] On pop-up that appears after clicking on grey 'Profile' button, change text in blue button from 'edit_user' to 'Edit user'
- [ ] On Add Member:
   - [ ] Replace 'Profilbild' with 'Profile picture'
   - [ ] Replace 'E-post:' with 'Email:'
   - [ ] Replace 'user.telephonecontaclabel:' with 'Phone:'
   - [ ] Replace 'Registrera' with 'Register'
- [ ] On Categories:
   - [ ] Replace 'add_category' with 'Add category'
- [ ] On Preferences:
   - [ ] Replace 'NÄTVERKSINSTÄLLNINGAR' with 'Network Settings'
   - [ ] Replace 'Transaktionsavgift' with 'Transaction fee (%)'
   - [ ] Replace 'Säljare procentsats' with 'Sales percentage'
   - [ ] Replace 'Köpare procentsats' with 'Purchase percentage'
   - [ ] Replace 'Ränta på BSEK' with 'Interest rate on negative balances (%)'
   - [ ] Replace 'Procentsats' with 'Percentage'
   - [ ] Replace 'Default balance limits' with 'Default credit limits'
   - [ ] Replace 'Maximum' with 'Positive'
   - [ ] Replace 'Minimum' with 'Negative'

**Comment by EugeneJoe** [comment]
@tfwoodroofMCS Can't quite find this one:
 `Replace instances of 'bKr' under 'Balance' in table with credit unit (abbreviated version)`

**Comment by tfwoodroofMCS** [comment]
@EugeneJoe 

![Image](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/1f7896f0-e0fa-4da1-8bef-57e8675d2ac5)

**Comment by tfwoodroofMCS** [comment]
- [ ] Balances need to be read from cc-node
- [ ] `credit unit` (abbreviated - search for 'tkn') comes from en-LCC.json

**Comment by tfwoodroofMCS** [comment]
`Balance` and `credit unit` not displaying correctly:

![Image](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/4792d5bd-4429-4e64-9098-58c049fe501c)

**Comment by tfwoodroofMCS** [comment]
'edit_user' yet to be replaced with 'Edit user' in Profile pop-up. Profile picture also not displaying properly:

![Image](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/7183d8a6-2b5c-45bc-9cdd-cbfb8919811a)

**Comment by tfwoodroofMCS** [comment]
'Logotyp' needs to be replaced with 'Profile picture' in pop-up after clicking on edit user button. Profile picture also not displaying properly:

![Image](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/bd1e0d0b-00f5-4688-b8e2-9d5287dabbf6)

**Comment by tfwoodroofMCS** [comment]
In Categories, 'add_category' yet to be replaced with 'Add category'. 'billingnamelabel' needs to be replaced with 'Category':

![Image](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/3ed1fadf-9f7a-4f70-862e-9ee026b77f79)

**Comment by tfwoodroofMCS** [comment]
Placeholder texts in Preferences need to be changed from variable names to texts (see original issue description):

![Image](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/e631d99d-4025-4f40-89a3-643fdea7a275)

**Comment by EugeneJoe** [comment]
Responded to!

**Comment by tfwoodroofMCS** [comment]
Thanks! If you could get a pull request in asap then we'll nearly be ready for the final language review.
