### ISSUE TITLE
We need to remove/fix Swedish in the Welcome email.

### ISSUE THREAD

**Issue by utunga** [CredComSoc/CreditCoopTech#83]
Swedish gets sent in the welcome email. 

![Image](https://user-images.githubusercontent.com/166867/262285315-d45cc1d2-3ac4-447c-9831-f443178ef8e2.png)

cf: #28

**Comment by tfwoodroofMCS** [comment]
- [ ] Change subject to 'Welcome to Land Care Trade'
- [ ] Change text beginning 'Du får det...' to 'You are receiving this email because you have requested to join Land Care Trade. Please click the following link or paste it into a browser to complete the sign up process:'
- [ ] Change text beginning 'Dina innloggningsuppgifter år:' to 'Your login details are:'
- [ ] Change 'E-postaddress:' to 'Email address:'
- [ ] Change 'Lösenord:' to 'Password:'
- [ ] Change 'Med vänliga hälsningar, Svensk Barter' to 'Best wishes, Land Care Trade'
